parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: superbb
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 27ee2660d691fd148c28b43b5a84b601
    database_path: null
